@extends('layouts.app')

@section('title', 'Total Sales Report')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Total Sales Report</h3>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('exportTotalSales') }}" method="POST" class="mb-4">
                            @csrf
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="start_date">Start Date</label>
                                        <input type="date" name="start_date" id="start_date"
                                            class="form-control @error('start_date') is-invalid @enderror"
                                            value="{{ old('start_date') }}" required>
                                        @error('start_date')
                                            <span class="invalid-feedback">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="end_date">End Date</label>
                                        <input type="date" name="end_date" id="end_date"
                                            class="form-control @error('end_date') is-invalid @enderror"
                                            value="{{ old('end_date') }}" required>
                                        @error('end_date')
                                            <span class="invalid-feedback">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="status">Order Status</label>
                                        <select name="status" id="status" class="form-control">
                                            <option value="DELIVERY">Delivered</option>
                                            <option value="PENDING">Pending</option>
                                            <option value="ALL">All</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary">Generate Report</button>
                                </div>
                            </div>
                        </form>

                        @if (isset($data))
                            <div class="card mt-4">
                                <div class="card-body">
                                    <h5 class="card-title">Report Summary</h5>
                                    <p class="card-text">Period: {{ $data['startDate'] }} to {{ $data['endDate'] }}</p>
                                    <p class="card-text">Generated by: {{ $data['user'] }} on {{ $data['today'] }}</p>

                                    <!-- Sales by User Table -->
                                    <div class="table-responsive mt-3">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Sales Representative</th>
                                                    <th>Order Count</th>
                                                    <th>Total Quantity</th>
                                                    <th>Total Gifts</th>
                                                    <th>Total Sales Amount</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($data['userSales'] as $userSale)
                                                    <tr>
                                                        <td>{{ $userSale['user_name'] }}</td>
                                                        <td>{{ number_format($userSale['order_count']) }}</td>
                                                        <td>{{ number_format($userSale['quantity']) }}</td>
                                                        <td>{{ number_format($userSale['gifts']) }}</td>
                                                        <td>{{ number_format($userSale['sales'], 2) }}</td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                            <tfoot>
                                                <tr class="table-dark">
                                                    <th colspan="2">Grand Total</th>
                                                    <th>{{ number_format($data['totalQuantity']) }}</th>
                                                    <th>{{ number_format($data['totalGifts']) }}</th>
                                                    <th>{{ number_format($data['totalSales'], 2) }}</th>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>

                                </div>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Set default dates
            const today = new Date();
            const firstDayOfMonth = new Date(today.getFullYear(), today.getMonth(), 1);

            document.getElementById('start_date').value = firstDayOfMonth.toISOString().split('T')[0];
            document.getElementById('end_date').value = today.toISOString().split('T')[0];
        });
    </script>
@endpush
